### ISSUE TITLE
Preferences dialogue box spills into panel area

### ISSUE THREAD

**Issue by ramansarda2000** [lxqt/qterminal#587] opened 2019-05-08 03:31 UTC
##### Expected Behavior : The qterminal preferences dialogue box should be within the boundaries and lxpanel.

When opened, qterminal preferences dialogue box should not spill vertically into lxpanel area.

##### Current Behavior : The qterminal preferences dialogue box spills vertically into lxpanel area.

Whether maximized or not, the qterminal preferences window spills vertically into lxpanel and below that. This leads to not able to access the options at the bottom (Okay, Apply and Close) and terminal margin option in the options tab. Refer to the screenshots attached.

![terminal](https://user-images.githubusercontent.com/37928641/57347310-78974980-716f-11e9-85a4-19d8b314f416.jpg)

![terminal prefs](https://user-images.githubusercontent.com/37928641/57347335-8ea50a00-716f-11e9-9962-ca804dfa3920.jpg)

##### Steps to Reproduce (for bugs)

1. Open qterminal. Go to File -> preferences
2. Go to appearance.
3. Notice the option "Terminal margin" at the bottom is below lxpanel
4. Also notice that the buttons Okay, Close and Apply are also below the panel and not accessible.

##### Context : Can't change Terminal margin

To change that option I have to autohide the lxpanel and then I can access it.

##### System Information

* Distribution & Version: Lubuntu 19.04
* Kernel: 5.0.0-13-generic
* Qt Version: 0.14.1 
* Package version: 0.14.1

**Comment by yan12125** [comment] 2019-05-08 03:38
> BTW, I didn't consider the title-bar height here because it couldn't be found in a reliable way for all window managers. I could have made room for 50 px but, IMO, it's unimportant.

(https://github.com/lxqt/qterminal/pull/575#issuecomment-473672266)

Besides the title bar, the panel is also an issue!

@tsujan: Do you think it's fixable in a reliable way?

**Comment by tsujan** [comment] 2019-05-08 03:52
@yan12125 I think @ramansarda2000 doesn't have the patch; in other words, I think this is a duplicate of the issue we already fixed and can be closed.

Apart from that, the title-bar height can be added to the calculation -- I could do that -- but I really don't think it's @ramansarda2000's problem. (Panel is automatically excluded from the available geometry.)

**Comment by tsujan** [comment] 2019-05-08 03:56
He says:
> The preferences window can be resized to use less vertical space by default and a scrollbar is required.

Definitely a duplicate of https://github.com/lxqt/qterminal/issues/574

**Closed by tsujan** 2019-05-08 03:56 UTC

**Comment by yan12125** [comment] 2019-05-08 03:59
Oh, I misunderstood the problem. As I can still see qterminal's preferences window overlapped with lxqt-panel in git-master, I thought the panel is not handled. Thanks for clarification!

**Comment by tsujan** [comment] 2019-05-08 04:03
@yan12125 
You're welcome.
The problem was height + lack of scrollbar. It's fixed.

@ramansarda2000 
I don't know when the fix will come to Lubuntu but it can't be soon. Maybe you could use a git package from PPA. You could ask Ubuntu.

**Comment by ramansarda2000** [comment] 2019-05-08 04:06
Hey! You mentioned that fix is released but then why does the terminal preferences window spill at bottom even now?

**Comment by tsujan** [comment] 2019-05-08 04:11
Fixing is different from releasing. The fix is in the latest git QTerminal. Those who use git packages have it. Of course, it'll be in the next official release too but a release doesn't happen with every fix.

Users of rolling distros can always have latest git LXQt. Ubuntu isn't a rolling distro but has PPA instead.

**Comment by tsujan** [comment] 2019-05-08 04:14
@yan12125 Whenever you felt that the title-bar height should also enter the calculation, please tell me!

**Comment by yan12125** [comment] 2019-05-08 15:59
I think it will be great to have the height of the title bar included. If getting the actual height is infeasible, assuming it 50px is also fine :)

**Comment by tsujan** [comment] 2019-05-08 16:09
I'll try the current git on Debian Buster that I installed on VirtualBox without guest extensions last night. I don't think anyone could have a smaller screen. But first, I should remember how to install build dependencies on Debian.

**Comment by yan12125** [comment] 2019-05-08 16:25
Well, I just change the screen resolution and the font size when testing that patch :)

**Comment by tsujan** [comment] 2019-05-08 16:36
To me, screen resolution isn't something I want to mess with ;) Moreover, the situation is more realistic on VirtualBox (a small monitor and reasonable font/icon size).

As for titlbar height and other WM things, they can be calculated by subtracting `QWidget::geometry()` from `QWidget::frameGeometry()` but there may be complications because the winnow isn't shown yet.

**Comment by tsujan** [comment] 2019-05-08 17:42
This is with a 800×600 virtual monitor, on the nice Debian Buster ISO @agaida has made:

![1](https://user-images.githubusercontent.com/981076/57395632-db272e80-71dd-11e9-9cdc-9e186475d24e.png)

I was able to resize the window from its title-bar. This is with the minimum height possible:

![2](https://user-images.githubusercontent.com/981076/57395641-e1b5a600-71dd-11e9-886c-408d82a04dca.png)

So, I think considering the title-bar height isn't necessary (because the window can be made smaller by the user) but good. Will modify the code, test it on VirtualBox and make a PR.

If a user finds a monitor with a resolution less than 800×600, he should accept the consequences ;) because the settings window cannot be made smaller even with the scrollbar.

**Comment by tsujan** [comment] 2019-05-08 20:46
The PR is here: https://github.com/lxqt/qterminal/pull/588

I also made it possible to fit the dialog into screens found by archeological excavations.

And, please, set the default installation prefix to `/usr` — it's hard to type `cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr` every time something should be tested on VirtualBox ;)
