### ISSUE TITLE
Qterminal takes too long to lunch 

### ISSUE THREAD

**Issue by mohsensama** [lxqt/qterminal#775] opened 2020-12-24 07:35 UTC
Qterminal is taking too much to lunch ( about 30s) and i have no idea what is the issue 

Mint 20 , cinnamon DE , Qterminal version  0.14.1 ,

 here is the LOG : 
 qt5ct: using qt5ct plugin
Properties constructor called
TRANSLATIONS_DIR: Loading translation file "qterminal_en_US.qm" from dir /usr/share/qterminal/translations
load success: false
qt5ct: D-Bus global menu: no
QDir::exists: Empty or null file name
Canot open file "/home/mohsen/.config/qterminal.org/qterminal_bookmarks.xml"
Trying to load translation file from dir "/usr/share/cinnamon"
Trying to load translation file from dir "/usr/share/gnome"
Trying to load translation file from dir "/home/mohsen/.local/share/flatpak/exports/share"
Trying to load translation file from dir "/var/lib/flatpak/exports/share"
Trying to load translation file from dir "/usr/local/share"
Trying to load translation file from dir "/usr/share"
Trying to load translation file from dir "/usr/share/qtermwidget5/translations"
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
Shell program: "/usr/bin/fish"
("/usr/bin/fish")
Properties destructor called

**Comment by stefonarch** [comment] 2020-12-24 08:07
qterminal_en_US.qm" does not exist in /usr/share/qterminal/translations
0.14.1 is way old too.

Did you ever try to launch it using` sudo qterminal`? 
Never launch a GUI app con sudo. You may fix your permissions in your home directory then.

This doesn't look like a qterminal issue. Not sure about the language,   with `LANGUAGE=en_US qterminaI ` I cannot reproduce.

Probably this should go in "Discussions".

**Comment by tsujan** [comment] 2020-12-24 09:08
We don't support old versions. Closing...

**Closed by tsujan** 2020-12-24 09:08 UTC
