### ISSUE TITLE
[Feature request] Option to not exit on execution

### ISSUE THREAD

**Issue by es20490446e** [lxqt/qterminal#1089] opened 2023-12-18 16:07 UTC
Maybe `qterminal` could have an option to explicitly not exiting on command execution when launched externally and graphically, so these issues don't happen:

https://github.com/lxqt/qterminal/issues/554
https://github.com/lxqt/pcmanfm-qt/issues/1842

**Comment by tsujan** [comment] 2023-12-18 16:13
As you already know, this is a duplicate of https://github.com/lxqt/qterminal/issues/554. @yan12125 (the main developer of QTerminal) closed that report, meaning that there's no plan for adding such an option. He might reopen the original report if, for any reason, he reconsiders it.

**Closed by tsujan** 2023-12-18 16:13 UTC
