### ISSUE TITLE
Closing a tab closes the entire program in dropdown mode.

### ISSUE THREAD

**Issue by cljacobs** [lxqt/qterminal#436] opened 2018-06-29 16:29 UTC
As per the title, whenever a tab is closed using the "close tab" button from a dropdown `qterminal`, all other tabs are closed and the program exits. This appears to happen only for terminals that are opened with `--drop` and doesn't happen if the tab is "closed" via the command `exit`.

I looked into the `journalctl` logs and found the following entries from the event:

```
Jun 29 12:05:25 thoth qterminal[15899]: Properties destructor called
Jun 29 12:05:25 thoth kwin_x11[926]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 35054, resource id: 44040230, major code: 18 (ChangeProperty), minor code: 0
Jun 29 12:05:25 thoth kwin_x11[926]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 35055, resource id: 44040202, major code: 15 (QueryTree), minor code: 0
Jun 29 12:05:25 thoth kwin_x11[926]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 35165, resource id: 46137350, major code: 15 (QueryTree), minor code: 0
Jun 29 12:05:25 thoth kwin_x11[926]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 35239, resource id: 4202746, major code: 10 (UnmapWindow), minor code: 0
Jun 29 12:05:25 thoth kwin_x11[926]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 35246, resource id: 4202746, major code: 4 (DestroyWindow), minor code: 0
```

It looks like whatever "properties destructor called" is doing is causing the issue here. When a tab in a qterminal in "normal" mode is closed there is no call to the properties destructor; or at least, none that appear in the logs and hence no QXcbConnection events either.

##### System Information

* Distribution & Version: Arch Linux (rolling release)
* Kernel: 4.17.2-1-ARCH
* Qt Version: 5.11.1-1
* libqtxdg Version:  3.2.0-3
* qtermwidget Version: 0.9.0-1
* lxqt-build-tools Version: N/A
* Package version: 0.9.0-1

**Comment by yan12125** [comment] 2018-06-29 16:43
Thanks for the report. This was previously reported and discussed in https://github.com/lxqt/qterminal/issues/154

**Comment by tsujan** [comment] 2018-06-29 16:48
@yan12125 Are you sure they are about the same thing? This is about multiple tabs and is rather like an old issue that's fixed before V0.9.0. I can't reproduce it as @cljacobs described.

**Comment by cljacobs** [comment] 2018-06-29 16:50
Hi @yan12125 

Perhaps I'm being particularly dense here, but I don't see where this previous report is in the linked issue? The issue I'm seeing is that qterminal exits even when there are multiple tabs still open, not when the last tab is closed.

**Comment by yan12125** [comment] 2018-06-29 16:55
Sorry I indeed misunderstood your issue. I'll check both issues when I got to my Linux box tomorrow.

**Comment by agaida** [comment] 2018-08-16 19:43
can't reproduce with debian and latest git, arch test follows.

**Comment by Geo25rey** [comment] 2018-10-29 10:16
I'm having trouble reproducing this issue on arch. I open QTerminal in drop-down mode and open a bunch of tabs (7+) then close all of them with all the methods I can think of: Ctrl+D, Ctrl+Shift+W, File->"Close Tab". Is this a dead issue?

**Comment by yan12125** [comment] 2018-10-29 11:03
Still reproducible on Arch with Qt 5.12.0 beta 3. You need to hit the red X button to reproduce the issue.

**Comment by Geo25rey** [comment] 2018-10-29 11:50
I just did that, but still no crash. Maybe it's because I haven't updated in like 2 weeks... I'm running Qt 5.11.2

**Comment by javimixet** [comment] 2019-12-22 11:47
Arch 5.4.3-arch1-1
Qt 5.13.2
qterminal 0.14.1

**method -> closes**
`exit` -> tab
ctrl+d -> tab
ctrl+shift+w -> all
file>"Close tab" -> all
Close button -> all

**Comment by DanielSmedegaardBuus** [comment] 2020-03-24 07:27
I'm seeing this problem on Lubuntu 20.04, and it's very frustrating :D 

Closing either with ctrl+w or clicking on the close button in a tab closes qterminal entirely. Ctrl+d'ing closes the session and the tab correctly. It does not happen in non-dropdown mode. Please advise how I can help with info.

Version installed: `0.14.1-0ubuntu2`

**Comment by DanielSmedegaardBuus** [comment] 2020-03-24 12:56
It's actually worse than this. Ctrl+W closes the terminal as well, so for instance trying to search for something in nano will close down qterminal as well :D

**Comment by pushqrdx** [comment] 2021-05-07 23:41
having the same issue, both ctrl+d and closing last tab closes qterm dropdown and the shortcut doesn't work anymore, i have to rerun QTerminal Dropdown on lxqt

**Comment by tsujan** [comment] 2022-02-20 12:43
Fixed in https://github.com/lxqt/qterminal/commit/004f1ddb8ca828399aa6f9b56b608199f9dddc8b

**Closed by tsujan** 2022-02-20 12:43 UTC
Labels: bug
