### ISSUE TITLE
Tab title stays the same after user switch with su

### ISSUE THREAD

**Issue by aramazano** [lxqt/qterminal#416] opened 2018-05-01 23:57 UTC
When I switch to root via `su -` tab title still shows original user name. It would be nice if the tab read as `root@torik:~`. This is particularly important (for me) for root sessions in order not to get frisky with command line with root privileges inadvertently. Please see the pic.
![qterm-1](https://user-images.githubusercontent.com/34963702/39499067-7d7f6c78-4db4-11e8-8349-0dd972990a61.png)

#### System Information
* Distribution & Version: LXQt [experimental-snapshots](https://lxqt.debian.net/) on top of Debian Testing (Buster)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.10.1
* qtermwidget Version: n/a
* qtermwidget5-data Version: 0.8.1~24-g4cc05f9-1
* lxqt-build-tools Version: Not installed
* qterminal Version: 0.8.1~36-g1a4452a-1

**Comment by tsujan** [comment] 2018-05-02 01:06
That isn't caused by QTerminal. You need a sudo font-end, like gksudo.

As an LXQt member, I shouldn't say, "don't use `lxqt-sudo`," but that's exactly what I say, unless you apply this patch: https://github.com/lxqt/lxqt-sudo/pull/30/files; without it, `lxqt-sudo` is nothing but trouble.

**Comment by palinek** [comment] 2018-05-02 06:52
IMO this isn't about the QTerminal, but about your (root) shell configuration - it doesn't send the needed escape sequences with "title"...

**Comment by tsujan** [comment] 2018-05-02 12:52
@palinek is right. The title depends on what is in your `/root/.bashrc` and is the same for all terminal emulators (QTerminal, Konsole, Terminology, xterm,...). There are many explanations about shell customization on the Internet. Closing this again.

**Closed by tsujan** 2018-05-02 12:52 UTC
