### ISSUE TITLE
Unable to launch latest [master]

### ISSUE THREAD

**Issue by SchweinDeBurg** [lxqt/qterminal#323] opened 2017-05-02 09:56 UTC
Console shows the following output:

```
[elijah@santiago ~]$ qterminal &
[1] 24122
[elijah@santiago ~]$ QDir::exists: Empty or null file name
QDir::exists: Empty or null file name
QDir::exists: Empty or null file name
QObject::connect: No such slot TabWidget::addNewTab()
QObject::connect:  (receiver name: 'consoleTabulator')

[1]+  Segmentation fault      (core dumped) qterminal
```

**Comment by yan12125** [comment] 2017-05-02 11:34
Seems it's broken with e826d7b3f5e0b72dc85d7e9d7e0aeb6e2f33d89a. Could you have a look? @pas2k

**Comment by agaida** [comment] 2017-05-02 11:42
One will need the current termwidget first - and build against the widget. Should work(TM) fine.

**Comment by yan12125** [comment] 2017-05-02 12:18
This is what I get - some warnings about ```TabWidget::addNewTab```. I guess it's not the cause of a crash, but it should be fixed as File -> New Tab From Preset -> Terminal doesn't work now.
```
$ qterminal
TRANSLATIONS_DIR: Loading translation file "qterminal_en_US.qm" from dir /home/yen/usr/share/qterminal/translations
load success: false
Properties constructor called
QDir::exists: Empty or null file name
Canot open file "./qterminal_bookmarks.xml"
QObject::connect: No such slot TabWidget::addNewTab() in /home/yen/Projects/qterminal/src/mainwindow.cpp:308
QObject::connect:  (receiver name: 'consoleTabulator')
Trying to load translation file from dir "/home/yen/.local/share"
Trying to load translation file from dir "/usr/local/share"
Trying to load translation file from dir "/usr/share"
Trying to load translation file from dir "/home/yen/usr/share/qtermwidget5/translations"
default KB_LAYOUT_DIR:  "/home/yen/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
Using color-schemes:  ("/home/yen/usr/share/qtermwidget5/color-schemes/", "/home/yen/.config/qterminal.org/color-schemes/")
Using color-schemes:  ("/home/yen/usr/share/qtermwidget5/color-schemes/", "/home/yen/.config/qterminal.org/color-schemes/")
Shell program: "/usr/bin/zsh"
("/usr/bin/zsh")
```

**Comment by pas2k** [comment] 2017-05-02 12:31
Created a pull request for the 1 Terminal preset situation. The segfault seems unrelated neither to it, nor to e826d7b3f5e0b72dc85d7e9d7e0aeb6e2f33d89a.

**Comment by pas2k** [comment] 2017-05-02 12:41
As for the issue, do
```
gdb --args qterminal
(gdb) run

(Process stopped with SIGSEGV)
(gdb) bt
```
The place of the error and places where modules installed will be shown. Post those here. In case libqtermwidget is not located in /usr/local/lib, chances are you are using an outdated library, like @agaida  says.

**Comment by agaida** [comment] 2018-07-15 01:39
Can't reproduce anymoe

**Closed by agaida** 2018-07-15 01:39 UTC
Labels: feedback required
