### ISSUE TITLE
Obscured font prompt under preferences in dropdown terminal

### ISSUE THREAD

**Issue by ianfarrell47** [lxqt/qterminal#969] opened 2022-07-21 04:29 UTC
##### Expected Behavior
From the dropdown terminal, the 'Select Terminal Font' prompt (under right click menu -> Preferences -> change font), should be the topmost window.

##### Current Behavior
'Select Terminal Font' prompt is below both the qterminal dropdown and the terminal settings window.

##### Steps to Reproduce (for bugs)
1. `qterminal --drop`
2. Right click menu -> Preferences
3. Change font

##### Context
I don't know if this is due to either Qt (version 5.15.5+kde+r172), my window manager, Openbox (version 3.6.1-8), or my Qt style (Breeze 5.25.3).

This bug doesn't appear on qterminal when not in dropdown mode.

##### System Information
LXQt 1.1

**Comment by stefonarch** [comment] 2022-07-21 06:01
I remember this being an issue time ago but fixed in the mean time. No issue with kwin here.

**Comment by stefonarch** [comment] 2022-07-21 07:43
While updating my VM with Lubuntu 22.04 which uses openbox I can confirm this, you need to lower the "Preferences" window to set the font.

**Comment by tsujan** [comment] 2022-07-21 10:03
Font dialog is a Qt modal dialog. The app doesn't position it (as it shouldn't); it just calls `QDialog::exec()`. A WM that puts such a modal dialog behind another window has a problem. Of course, Openbox's problem will never be fixed because its development was stopped a long time ago.

If you see this problem with an alive WM too, you might want to report it to its developers.

**Closed** 2022-07-21 10:05 UTC

**Comment by stefonarch** [comment] 2022-07-21 11:19
I tested in VM with xfwm4 and it's even worse: the font window is behind the dropdown window, and to get out of the block you have to use esc or kill all of it.

**Comment by tsujan** [comment] 2022-07-21 12:10
I think there may be workaround, but there's no guarantee that it'll circumvent all problems of all WMs: We can make the font dialog window-modal, instead of app-modal (in Qt's terms). I might make a test PR later.
