### ISSUE TITLE
Qterminal dropdown placed vertically centered when Width=100% on Xfwm4

### ISSUE THREAD

**Issue by isf63** [lxqt/qterminal#1043] opened 2023-04-01 16:27 UTC
##### Expected Behavior
Dropdown terminal when Width=100% is anchored to the top of the desktop

##### Current Behavior
Terminal is vertically centered

##### Steps to Reproduce (for bugs)
1. Use the Xfwm4 window manager
2. Launch Qterminal dropdown and set Width=100%
3. Press activate shortcut twice to re-show

##### System Information

* QTerminal version: 1.2.0
* Distribution & Version: Arch Linux
* Kernel: Linux 6.2.8
* Qt Version: Arch latest
* Xfwm4 version: 4.18.0

**Comment by stefonarch** [comment] 2023-04-01 21:05
Duplicate of https://github.com/lxqt/qterminal/issues/1019 I guess

**Closed by stefonarch** 2023-04-01 21:05 UTC
