### ISSUE TITLE
How to start qterminal with terminal splitted

### ISSUE THREAD

**Issue by onekk** [lxqt/qterminal#99] opened 2014-11-24 15:31 UTC
Hi, I want to open qterminal in this manner:

![screen](https://cloud.githubusercontent.com/assets/7129964/5180412/b18e7032-748b-11e4-8da9-41d69a8843ff.png)

With the GUi i have to split horizontally and then vertically.

Carlo D.

**Comment by danielmofer** [comment] 2021-05-15 15:57
Did you solve it?

**Comment by tsujan** [comment] 2021-05-15 16:09
This is a duplicate of https://github.com/lxqt/qterminal/issues/351. QTerminal has presets and they're work at startup after https://github.com/lxqt/qterminal/pull/831 is merged.

**Closed by tsujan** 2021-05-15 16:09 UTC
Labels: feature requests
