### ISSUE TITLE
Qterminal dropdown closes on selecting external preferences

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qterminal#779] opened 2020-12-28 16:18 UTC
Continues from here https://github.com/lxqt/qtermwidget/pull/385#issuecomment-751666223
Probably found the hidden factor testing a clean user.

##### Expected Behavior

Changing settings is possible from both qterminal and -dropdown
##### Current Behavior

Qterminal dropdown closes immediately after selecting font, bookmarks file or background img showing or not showing confirmation closure dialog which doesn't work and always closes application. And shouldn't open anyway.

##### Steps to Reproduce (for bugs)

1. Make sure in preferences > behavior "ask for confirmation to exit" is set to yes
2. Change font or bookmarks file (font window opens  below (another issue) so move it using taskbar)
3. Hit ok
4. Dialog for closure window opens , and anything you select will close qterminal dropdown

##### System Information

* Distribution & Version:  debian, arch, latest git

EIDT: BTW I see now that just typing "exit" dialog is shown and if answer is "don't close" terminal gets white and irresponsible (happens only  in dropdown), confirmation dialog from File > exit is working fine.

**Comment by tsujan** [comment] 2020-12-28 16:45
What do you mean by *external* preferences? If you use the preferences dialog of an ordinary instance QTerminal, the drop-down instance should disappear because it gets unfocused.

**Comment by tsujan** [comment] 2020-12-28 16:57
OK, "external" aside, I can reproduce the issue.

**Comment by tsujan** [comment] 2022-02-20 12:39
Fixed in https://github.com/lxqt/qterminal/commit/004f1ddb8ca828399aa6f9b56b608199f9dddc8b

**Closed by tsujan** 2022-02-20 12:39 UTC
Labels: bug
