### ISSUE TITLE
"highlight all matches" not working

### ISSUE THREAD

**Issue by anilFree** [lxqt/qterminal#622] opened 2019-08-30 18:07 UTC
In find ui, there is an option to "highlight all matches", it doesn't work at all.
only one match is highlighted.

qterminal version 0.14.1
qt version 5.11.3
distro: debian unstable

**Comment by tsujan** [comment] 2019-08-31 08:42
Confirming.

I'm not sure if it stopped working after a commit or never worked.

**Comment by lameventanas** [comment] 2019-09-26 01:50
I hope this can be fixed soon.

**Comment by deathtrip** [comment] 2020-02-27 16:55
Yeah. not working for me either.

**Comment by stefonarch** [comment] 2020-12-18 09:43
Duplicate of https://github.com/lxqt/qterminal/issues/120

**Closed by stefonarch** 2020-12-18 09:43 UTC
