### ISSUE TITLE
qterminal keyboard operated scroll-back not working

### ISSUE THREAD

**Issue by uffejakobsen** [lxqt/qterminal#741] opened 2020-11-18 23:24 UTC
qterminal keyboard operated scroll-back not working

In qterminal-0.15 and earlier versions it was possible to traverse the scroll-back buffer (history) using SHIFT+PGUP/PGDN

This does not work with qterminal-0.16 - even with a history of 1000 lines you can only scroll back half a page using SHIFT+PGUP/PGDN

If you use the mouse to operate the scroll back slider it works as expected

Seen with qterminal-0.16 on ArchLinux

**Comment by yan12125** [comment] 2020-11-20 12:13
I cannot reproduce the issue with qterminal 0.16.1-1 on Arch Linux. Arelated change might be https://github.com/lxqt/qtermwidget/pull/352. Do you use a custom keyboard layout?

**Comment by uffejakobsen** [comment] 2020-11-20 13:15
I'm also on qterminal 0.16.1-1 on Arch Linux and I still see the problem...

>  Do you use a custom keyboard layout?
I'm not really sure what you refer to here - is it my keyboard language layout within the Desktop Env - then yes (Danish keyboard layout)

**Comment by yan12125** [comment] 2020-11-21 10:36
> A second option is the option inside qterminal called "emulation" in the "behaviour" section - is guess this is the target for your question ?

Yes that's what I'm asking. Sorry for not being clear enough.

> Anyway the emulation setting in qterminal is "default"

Hmm, that should work correctly.

Let's check if this is a regression first. I created an Arch Linux package with https://github.com/lxqt/qtermwidget/pull/352 reverted. Could you install that and see if the the issue persists?

[qtermwidget-0.16.1-1-x86_64.pkg.tar.zst.zip](https://github.com/lxqt/qterminal/files/5577424/qtermwidget-0.16.1-1-x86_64.pkg.tar.zst.zip)
(Uploaded as ZIP as GitHub does not like pkg.tar.zst)

**Comment by uffejakobsen** [comment] 2020-11-22 17:34
Hello, 
Thanks for your effort and clarification.
I accidentally stumbled over an explanation for the problem - without testing your library

The preferences option "Behavior" / "Action after paste" was the cause of the problem.
Setting it to "No move" enables me to traverse the whole scroll-back buffer operating by SHIFT+PGUP/PGDN
Changing the "Action after paste" to anything other than "No move" will give the behavior that started this issue/ticket

It doesn't really make any sense that this option should affect scroll-back keyboard operation
There is clearly something changed in with the new 0.16.x releases something have changed with the "Action after paste" setting since it has been set to "Move to end" in my configuration for years - and now that setting suddenly after updating to 0.16.x releases gives a new problem

Anyway I hope that you will be able to reproduce this problem from my description. 
At least we managed do that of 3 different Arch Linux installations :-)

**Comment by yan12125** [comment] 2020-11-23 04:17
> The preferences option "Behavior" / "Action after paste" was the cause of the problem.

Excellent findings! I can reproduce the issue, too.

**Comment by yan12125** [comment] 2020-11-27 16:34
The issue is more complicated than it should be :/

Since https://github.com/lxqt/qterminal/pull/309, the "Action after paste" no longer works if not pasting via keyboard (e.g., via the context menu). It should be fixed first so that the "Action after paste" feature can be properly fixed to not inferfere scrolling via keyboard.

Another relevant bug: https://github.com/lxqt/qterminal/issues/43 - "Action after paste" has been problematic since long time ago.

**Comment by uffejakobsen** [comment] 2020-11-27 16:39
I've been hit and annoyed by issue #43 - but I found out that I seems to go away why I set action after paste to none

**Comment by yan12125** [comment] 2020-12-18 14:37
Sorry for the long delay - it should be fixed with the two pull requests linked above.

**Closed** 2021-01-08 16:23 UTC
Labels: bug, high priority

**Comment by yan12125** [comment] 2021-01-08 16:30
Sorry for the long delay, but it is finally fixed in git. In general we do not backport fixes to stable versions, especially for large ones like the linked ones above. You will need to build from git if you want to keep "Move to end" (now called "Scrolling to bottom") and  as well as use keyboard to scroll up. As you're using Arch Linux, AUR packages qtermwidget-git and qterminal-git, which are also maintained by me, should help.
