### ISSUE TITLE
qTerminal doesn't work well with tmux+powerline

### ISSUE THREAD

**Issue by mike-pt** [lxqt/qterminal#260] opened 2016-08-31 13:00 UTC
This was actually reported in #249 as you can see in the posted image:

https://cloud.githubusercontent.com/assets/2022397/17977161/900df01a-6abe-11e6-99e5-20a65963c346.png

I'm facing the exact same issue, and only with tmux+powerline, so I guess powerline is the issue, but this doesn't happen with any other of the terminal apps including xterm.

I've just recently started using qTerminal but I like it, and would prefer to used it, so it would be great if this could be fixed.

**Comment by yan12125** [comment] 2016-10-27 15:01
I guess my fork https://github.com/yan12125/qtermwidget/tree/merge-all may solve it. I'd like to try it. How did you install tmux+powerline?

**Comment by igor-astsakhov** [comment] 2016-10-27 15:36
tmux via repo:

$ dnf install -y tmux

powerline via pip:

pip install --user powerline-status

**Comment by yan12125** [comment] 2016-10-27 15:41
@igor-astsakhov I saw your .tmux.conf at https://github.com/lxde/qterminal/issues/249#issuecomment-242489126. However, seems Github does not display it correctly. Copying those lines into my tmux.conf brings lots of syntax errors. Could you paste your .tmux.conf to pastebin or like?

**Comment by igor-astsakhov** [comment] 2016-10-27 15:57
http://pastebin.com/D7Wb5LHd

**Comment by yan12125** [comment] 2016-10-27 16:52
I've just installed powerline and patched fonts. However, there are still lots of errors:
```
/home/yen/.tmux.conf:6: no current window
/home/yen/.tmux.conf:7: no current window
/home/yen/.tmux.conf:27: unknown option: status-utf8
/home/yen/.tmux.conf:33: unknown option: status-utf8
/home/yen/.tmux.conf:49: no current window
/home/yen/.tmux.conf:50: no current window
```

After commenting out offending lines, the layout is missing something:
![tmux-qterminal](https://cloud.githubusercontent.com/assets/1937689/19776974/bf1f8f14-9ca8-11e6-92d7-2148398a6e2c.png)


I use tmux 2.3 provided by Arch Linux. Which version are you using?

**Comment by igor-astsakhov** [comment] 2016-10-27 17:04
tmux-2.1-3.fc23.x86_64

Looks like these lines are not being applied (they're single lines in the
config):

set -g window-status-format
"#[$_POWERLINE_WINDOW_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER_SPACES#I
#[$_POWERLINE_WINDOW_DIVIDER_COLOR]$_POWERLINE_LEFT_SOFT_DIVIDER#[default]#W
$_POWERLINE_LEFT_HARD_DIVIDER_SPACES"

set -g window-status-current-format
"#[$_POWERLINE_WINDOW_CURRENT_HARD_DIVIDER_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER#[$_POWERLINE_WINDOW_CURRENT_COLOR]#I
$_POWERLINE_LEFT_SOFT_DIVIDER#[$_POWERLINE_WINDOW_NAME_COLOR]#W
#[$_POWERLINE_WINDOW_CURRENT_HARD_DIVIDER_NEXT_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER"

set -g status-left "#[$_POWERLINE_SESSION_COLOR] #S
#[$_POWERLINE_SESSION_HARD_DIVIDER_NEXT_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER#(eval
\$POWERLINE_COMMAND tmux left)"

But its not skipping so that is good, I will try the newer version.

I also use powerline on the bash command line.

**Comment by yan12125** [comment] 2016-10-28 03:49
I find the problem. This is a tmux bug and I'll report it there.

In brief: powerline uses the [watch character](http://www.fileformat.info/info/unicode/char/231a/index.htm) (0x231a). Since Unicode 9.0.0, this character is wide (size = 2), while tmux [assumes it's narrow](https://github.com/tmux/tmux/blob/master/compat/utf8proc.c#L38), so printing it breaks some terminals.

**Comment by yan12125** [comment] 2016-10-28 12:30
Submitted pull request to https://github.com/tmux/tmux/pull/615

**Comment by igor-astsakhov** [comment] 2016-10-28 13:47
Not sure if that is the cause, it appears every time the uptime increments
that powerline status line
reprints in the terminal.

I changed the configuration which removed the clock:

$ cp unicode_terminus.json powerline.json
$ pwd
~/.config/powerline/themes


​

**Comment by yan12125** [comment] 2016-10-28 13:53
How about changing these lines in ```powerline.json```:
```
		"time": {
			"before": "⌚ "
		},
```
to
```
		"time": {
			"before": " "
		},
```
⌚ (0x231a) is the offending character. Tmux has a mysterious assumption for this character than common terminals.

**Comment by igor-astsakhov** [comment] 2016-10-28 14:16
Yes, I tried that as well in my screenshot there is no clock. But it still
reprints the line.

**Comment by yan12125** [comment] 2016-10-28 14:38
I use my fork of QTerminal and tmux. Maybe both of them should be patched to get a working powerline. If you use Arch Linux or Manjaro, I can send you my patched tmux and qterminal packages.

**Comment by agaida** [comment] 2018-07-15 13:07
@yan12125 ?

**Comment by yan12125** [comment] 2018-09-28 07:19
This should have been fixed in the latest tmux if it's built against utf8proc. You may want to ask your distribution developers to enable that.

**Closed by yan12125** 2018-09-28 07:19 UTC

**Comment by wtgee** [comment] 2019-04-21 19:30
Hi, I'm confused as to what the fix is here. Fresh install of Lubuntu 19.04 with LXQt 0.14.1 and I am getting this on some of my remote servers. It does appear to be some character in the powerline but I haven't seen this happen before.

**Comment by yan12125** [comment] 2019-04-22 00:00
Hi @wtgee could you report your issue to Launchpad? It's not unusual that Lubuntu packages have issues due to something wrong in their packaging scripts, so I'd like to make sure it's really an upstream issue first.
