### ISSUE TITLE
bash_history is not saved if the terminal is closed by clicking the "x" button

### ISSUE THREAD

**Issue by Vaporeon** [lxqt/qterminal#369] opened 2017-11-01 20:05 UTC
##### Expected Behavior

The shell should append command history to this file on exit.
##### Current Behavior

No history for the current session is appended, suggesting bash does not exit cleanly when qterminal is closed this way. Exiting by typing "exit" works as intended.

##### Steps to Reproduce (for bugs)

Open qterminial and run a few commands, then close it with the mouse.

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 4.13.9
* Qt Version: 5.9.2 
* libqtxdg Vesion:  3.1.0
* qtermwidget Version: 0.8.0
* lxqt-build-tools Version: --
* Package version: 0.8.0

Packages installed from official repos.

**Comment by yan12125** [comment] 2017-11-01 20:25
Clicking X and bash history are written as expected on my machine. I have almost the same environment: Arch, kernel 4.13.10, Qt 5.9.2. qtermwidget and qterminal are built from git, which are only a few commits newer than official packages.

I have a rather complicated .bashrc. Not sure if it that makes a difference.

**Comment by Vaporeon** [comment] 2017-11-01 20:45
Hmm. There is nothing fancy about my .bashrc that would cause anything. I'm using LxQt with kwin if that matters at all.

**Comment by yan12125** [comment] 2017-11-01 20:49
OK I can reproduce the bug with an empty .bashrc. There's magic in my .bashrc :)

**Comment by guildem** [comment] 2018-01-07 08:44
Same here, even with a clean bashrc.
Are you able to share your magic .bashrc please ? ;)

**Comment by kghost** [comment] 2018-05-21 12:52
This bug belongs to qtermwidget.

These are what happened when closing qterminal:

* qterminal destroy qtermwidgets
* qtermwidget close pty
* pty send SIGHUP to bash
* qtermwidget destroy QProcess
* QProcess kill the bash

The problem is that QProcess will kill the process when destroy, there are 2 solutions:
* wait bash exit after sending SIGHUP, then destroy QProcess
* detach bash from QProcess when exit

**Comment by palinek** [comment] 2018-05-21 12:59
duplicate of lxqt/lxqt#1432

**Closed by palinek** 2018-05-21 12:59 UTC
Labels: bug, invalid
