### ISSUE TITLE
shrink a qterminal window and right-click Copy.Link.Address can produce invalid URLs

### ISSUE THREAD

**Issue by guiverc** [lxqt/qterminal#805] opened 2021-03-12 06:05 UTC
If you shrink the qterminal window, then right-click COPY.LINK.ADDRESS of a URL on the window, the URL that gets to the clipboard maybe incomplete

##### Expected Behavior
I'd expect either
- the correct URL is copied
- it refuses to copy the URL since it's no longer valid (not all shown)

Instead if copies the portion of it that is visible (if long, it may appear on multiple lines and it isn't always obvious it's incomplete on screen)

Of course I'd love for it the still COPY the URL as it originally appeared on screen, but if that isn't possible (due to a window re-size), I'd rather have it copy nothing/do-nothing

##### Current Behavior

Originally noticed on Lubuntu hirsute.  See https://bugs.launchpad.net/ubuntu/+source/qterminal/+bug/1918858

I ran a script that creates a file, then view the file with `cat`
```guiverc@d960-ubu2:~/uwn$ cat issues/673/microblog.txt
Issue 673 of the Ubuntu Weekly Newsletter is here! Covering the week of February 28 - March 6, 2021 https://wiki.ubuntu.com/UbuntuWeeklyNewsletter/Issue673```

Key bit I watched is "UbuntuWeeklyNewsletter"

On re-sizing the window it that part fo the text became
"UbuntuWewsletter"
re-size again
"Ubuntwsletter"
etc, each time with the copied LINK becoming shorter (& useless), ie.
"https://wikeklynewsletter/Issue673"

##### Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug,                --->
<!--- or ideas how to implement the addition or change                     --->

##### Steps to Reproduce (for bugs)

1.  Open qterminal (decent size)
2.  `cat /file` (or anything with a URL on it, a `echo https://wiki.ubuntu.com/UbuntuWeeklyNewsletter/Issue673` would work
3.  right-click & copy.link.address (all good)
4.  reduce window size (so the link isn't all shown)
5.  right-click & copy.link.address (no longer valid)

##### Context
Refer to the launchpad error.
On tuesday morning I ran a script that generates a file for pasting online.  I `cat` the generated file , but forgot to paste to all sites.
The next day (wednesday) I noticed I didn't paste everywhere, I went to the tab where I do UWN work & copy-link & pasted the URL knowing nothing had changed (never occurred to me a re-size of window changes the contents of qterminal functions)
Today I notice the paste done wednesday or in fact today is now an invalid URL.  I need to `cat` the file again to see the URL on my re-sized qterminal window

##### System Information
                                                       --->
* Distribution & Version: Lubuntu hirsute & opensuse tumbleweed (2021-02-22)
* Kernel: 5.10.0-14 & 5.10.16-1
* Qt Version: 5.15.2 & 5.15.2
* qtermwidget Version: libqtermwidget5-0:amd64(0.16.1-1ubuntu1)
* lxqt-build-tools Version: 
* Package version: 0.16.1-1ubuntu1 & 0.16.1-1.3

**Comment by guiverc** [comment] 2021-03-12 07:32
Same occurs in Fedora 33
LXQt 0.15.0
Qt 5.15.2
kernel 5.10.16

**Comment by tsujan** [comment] 2024-12-13 13:54
After checking the code, it seems to me that this is caused by https://github.com/lxqt/qterminal/issues/76.

**Comment by tsujan** [comment] 2024-12-13 21:06
Opened https://github.com/lxqt/qtermwidget/issues/576, which might remain open indefinitely, unless someone implements text wrapping before the last prompt. Closing…

**Closed by tsujan** 2024-12-13 21:06 UTC
Labels: bug
