### ISSUE TITLE
The qterminal F12 drop-down and hide doesn't work reliable

### ISSUE THREAD

**Issue by shirishag75** [lxqt/qterminal#491] opened 2018-10-13 11:57 UTC
I have been using guake . I tried qterminal because it has similar key-bindings esp. F12 . 

But that doesn't seem to work, especially when I want it to hide and use the space for other things. IIUC then the behavior should be click F12 once it will show qterminal, click F12 again it will disappear or hide but it doesn't seem to work :(

I am on Debian buster - 

```
Package: qterminal
Version: 0.9.0-3
Severity: normal



-- System Information:
Debian Release: buster/sid
  APT prefers testing-debug
  APT policy: (500, 'testing-debug'), (500, 'testing'), (100, 'unstable-debug'), (100, 'experimental-debug'), (100, 'experimental'), (100, 'unstable')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-1-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages qterminal depends on:
ii  libc6              2.27-6
ii  libqt5core5a       5.11.1+dfsg-9
ii  libqt5dbus5        5.11.1+dfsg-9
ii  libqt5gui5         5.11.1+dfsg-9
ii  libqt5widgets5     5.11.1+dfsg-9
ii  libqt5x11extras5   5.11.1-2
ii  libqtermwidget5-0  0.9.0-2
ii  libstdc++6         8.2.0-7
ii  libx11-6           2:1.6.6-1

Versions of packages qterminal recommends:
ii  qterminal-l10n  0.13.0-1

qterminal suggests no packages.

-- no debconf information

```

Some more info. from ~/.config/qterminal.org 

maybe I made some newbie mistake - 

```
$ cat qterminal.ini 
[General]
AskOnExit=true
BookmarksFile=/home/shirish/.config/qterminal.org/qterminal_bookmarks.xml
BookmarksVisible=true
Borderless=false
ChangeWindowIcon=true
ChangeWindowTitle=true
ConfirmMultilinePaste=false
HideTabBarWithOneTab=false
HistoryLimited=false
HistoryLimitedTo=1000000
KeyboardCursorShape=0
LimitTabWidth=true
LimitTabWidthValue=500
MenuVisible=true
MotionAfterPaste=0
SavePosOnExit=true
SaveSizeOnExit=true
ScrollbarPosition=2
ShowCloseTabButton=true
TabBarless=false
TabsPosition=0
Term=xterm-256color
TerminalBackgroundImage=
TerminalTransparency=0
TerminalsPreset=0
TrimPastedTrailingNewlines=false
UseBookmarks=false
UseCWD=false
colorScheme=Linux
emulation=default
enabledBidiSupport=true
fontFamily=DejaVu Sans Mono
fontSize=15
guiStyle=
highlightCurrentTerminal=true
showTerminalSizeHint=true
version=0.9.0

[DropMode]
Height=50
KeepOpen=false
ShortCut=F12
ShowOnStart=false
Width=99

[MainWindow]
ApplicationTransparency=0
pos=@Point(0 32)
size=@Size(640 480)
state=@ByteArray (some numbers, maybe might have some private info. hence deleted while sharing here.)

[Sessions]
size=0

[Shortcuts]
Add%20Tab=Ctrl+Shift+T
Bottom%20Subterminal=Alt+Down
Clear%20Active%20Terminal=Ctrl+Shift+X
Close%20Tab=Ctrl+Shift+W
Collapse%20Subterminal=
Copy%20Selection=Ctrl+Shift+C
Find=Ctrl+Shift+F
Fullscreen=F11
Hide%20Window%20Borders=
Left%20Subterminal=Alt+Left
Move%20Tab%20Left=Alt+Shift+Left|Ctrl+Shift+PgUp
Move%20Tab%20Right=Alt+Shift+Right|Ctrl+Shift+PgDown
New%20Window=Ctrl+Shift+N
Next%20Tab=Ctrl+PgDown|Ctrl+Tab
Paste%20Clipboard=Ctrl+Shift+V
Paste%20Selection=Shift+Ins
Preferences...=
Previous%20Tab=Ctrl+PgUp|Ctrl+Shift+Tab
Quit=
Rename%20Session=Alt+Shift+S
Right%20Subterminal=Alt+Right
Show%20Tab%20Bar=
Split%20Terminal%20Horizontally=
Split%20Terminal%20Vertically=
Toggle%20Bookmarks=Ctrl+Shift+B
Toggle%20Menu=Ctrl+Shift+M
Top%20Subterminal=Alt+Up
Zoom%20in=Ctrl++
Zoom%20out=Ctrl+-
Zoom%20reset=Ctrl+0

```

**Comment by tsujan** [comment] 2018-10-13 12:11
Perhaps `F12` is taken by another app on your system. Here, with the latest git version of QTerminal, I've assigned `F1` to that action and it works without problem.

Try to change the shortcut in Preferences → DropDown

**Comment by shirishag75** [comment] 2018-10-13 12:35
I changed the shortcut in Preferences > DropDown to F1 and still didn't have any effect. 

Just to check if my keyboard is working properly or not I did try https://unix.stackexchange.com/questions/120199/how-to-detect-global-key-presses

```
$ xev | grep -A2 --line-buffered '^KeyRelease' \
>     | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'
36 Return
67 F1
67 F1
67 F1
67 F1
^C

```

**Comment by agaida** [comment] 2018-10-13 14:33
@tsujan - we can admit that our implementation of a subterminal isn't par with guake and yakuake right now. One of the long standing glitches is the behaviour if the last open terminal is closed in drop down - so the whole terminal process terminate and is gone  - there is a long standing bugreport and iirc pull request to just open a new terminal in dropdown mode.

Not nice, but to be honest not one of our main probelms with qterminal right now. If i count right i put initial 112 open issuse into the qterminal/qtermwidget sprint, we are down to 84 right now. But any claim about the dropdown behaviour is likely right and we should find a better solution soon.

**Comment by tsujan** [comment] 2018-10-13 14:54
@agaida As you know, I'm not an active QTerminal dev but, once in a while, I find and fix its problems. In this case, I still don't understand why the dropdown mode works fine for me but not for @shirishag75 . That understanding is needed for finding the probable bug.

**Comment by shirishag75** [comment] 2018-10-13 15:01
One of the observations I had which I forgot to share is that whenever I use F12 it shows up as tilde . I again tried the global key press trick to see whether the key was mapped or registering some other letter but no, it shows as F12 -

```
$ $ xev | grep -A2 --line-buffered '^KeyRelease' \
>     | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'
$: command not found
shirish@debian:~$ xev | grep -A2 --line-buffered '^KeyRelease'  | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'
96 F12
96 F12
96 F12
96 F12

```

**Comment by tsujan** [comment] 2018-10-13 15:03
@shirishag75 Do you use QTerminal under LXQt?

**Comment by shirishag75** [comment] 2018-10-13 15:04
nope, under debian-mate .

**Comment by tsujan** [comment] 2018-10-13 15:10
Ah, the problem may be related to that.

**Comment by shirishag75** [comment] 2018-10-13 15:15
nope, it isn't. I just commented out the line in .xsessionrc  and still it shows F12 as tilde within qterminal.

**Comment by tsujan** [comment] 2018-10-13 15:30
> nope, it isn't. I just commented out the line in .xsessionrc and still it shows F12 as tilde within qterminal.

`F12` aside, you said the dropdown mode didn't work for you with any shortcut. That was why I said using QTerminal under mate was the cause, although I don't know how. And, of course, the problem may be in Qterminal itself.

**Comment by shirishag75** [comment] 2018-10-13 15:36
JFR, I straced out of it, maybe somebody can find something . 
[qterminal.tar.gz](https://github.com/lxqt/qterminal/files/2475590/qterminal.tar.gz)

I just did the following - 

1. In mate-terminal do $ strace -o qterminal.txt qterminal 
2. When qterminal opened, just pressed F12 key. 
3. Closed qterminal and terminated quit qterminal properly. 

The resulting file was 1.8 MB txt file  which I compressed using .gzip.  If anybody knows a better way, am open to listening.

**Comment by agaida** [comment] 2018-10-13 17:02
@shirishag75 feel free to ping me in OFTC #d-lxqt - i guess we can sort out the most of the problems

**Comment by agaida** [comment] 2018-10-13 17:19
@tsujan - have trust in @shirishag75 - iong term debian users, maintainers and developers have the abilitiy to run into bugs nobody has seen before at the first attempt :D

**Comment by tsimonq2** [comment] 2018-10-13 19:32
Lubuntu has [seen](https://bugs.launchpad.net/ubuntu/+source/qterminal/+bug/1795998) a lot of problems with this lately, so it's not just a MATE thing. :stuck_out_tongue:

**Comment by agaida** [comment] 2018-10-13 19:58
in case of Lubuntu the usual suspect is that the bug is in front of the screen - joke aside, dropdown isn't the most sophisticated solution.

**Comment by agaida** [comment] 2018-10-13 20:00
@shirishag75 - in oftc #debian-lxqt should be 8 or so people idling around

**Comment by agaida** [comment] 2018-10-13 20:34
@tsujan @yan12125 @tsimonq2 - what do you think - discussed it with pmattern years ago iirc. Imho we should split out the dropdown part and make it an application of it's own. That would maybe lead to some duplicated code, but not to much if we do this right.

**Comment by tsimonq2** [comment] 2018-10-13 20:46
ACK, so Lubuntu can just not ship it by default, problem solved. :stuck_out_tongue:

**Comment by agaida** [comment] 2018-10-13 20:48
hmm - btw, just checked out yakuake - ok - F12 work :sunglasses:. But they have other bugs that we have fixed long ago in qterminal - so it is the choice between pest and cholera

**Comment by tsujan** [comment] 2018-10-13 20:48
> Imho we should split out the dropdown part and make it an application of it's own.

I don't agree. IMHO, the dropdown mode is like bonus and code duplication would be very wrong.

**Comment by agaida** [comment] 2018-10-13 20:50
@tsujan - you should have a look into the codebase how dropdown is implemented - i know you are tough, but i was running away screaming last time i did.

**Comment by agaida** [comment] 2018-10-13 20:55
Ok - two applications would mean - we could use 99% of the existing code and would have only a new main for the drop down and some dropdown specific things different - so we should not have to musch duplicated code. If we do it right there should be 4-6 new files that do the trick and that should be legit. (At least i hope so)

**Comment by tsujan** [comment] 2018-10-13 21:01
I really enjoy the dropdown mode sometimes. It'll be unfortunate if I need to install another app for it :(

Unlike with libfm-qt and pcmanfm-qt, I've read qterminal codes only when I needed to deal with them but I can't believe there wouldn't be a lot of duplication. Moreover, if there's bug, splitting won't fix it or make it easier to fix automagically.

**Comment by agaida** [comment] 2018-10-13 21:07
ok - splitting would be an implementation detail, i don't see the need for installing a different application. Right now we provide two desktop files, one for qterminal and one for qterminal-dropdown. If you think we shouldn't split i'm fine with - but we should improve the dropdown if we want to have it longterm. Otherwise it would be disservice for our users.

just moved the new bugs to the qterm sprint row - we now have 86 bugs in. So any help is welcome.

**Comment by agaida** [comment] 2018-10-13 21:12
https://github.com/lxqt/qterminal/issues/316 - so the problem isn't exactly new

**Comment by shirishag75** [comment] 2018-10-14 13:11
btw just was in the channel, will be there a while and then sign out I guess but will try again tomorrow to see if I see you there, did ping you btw.

**Comment by agaida** [comment] 2018-10-14 22:05
First issue solved - qt5translations-l10n missed - this package was only recommended and is now a dependency. (For non-debian-users: apt install $foo --no-install-recommends is a really bad idea most of the time, default is install recommends)

**Comment by yan12125** [comment] 2018-10-15 02:35
> @tsujan @yan12125 @tsimonq2 - what do you think - discussed it with pmattern years ago iirc. Imho we should split out the dropdown part and make it an application of it's own. That would maybe lead to some duplicated code, but not to much if we do this right.

I'm with @tsujan - not a fan to get two applications, either. Splitting can bring maintenance burden.

Regarding the original issue - I have never reproduced it on Arch Linux + LXQt, and I'm too lazy to install other systems to test it, so I have never looked into it. Looks like @agaida has found a partial solution. But, how are keyboard shortcuts related to translations?

**Comment by shirishag75** [comment] 2018-10-15 06:02
I think this partial conversations with Agaida yesterday will make matters more clearer - 

> shirish
> 20:52 the good thing in this release is at least the shortcuts are responsive, it wasn't responsive at all in 0.9.0
> 
> A agaida (IRC)
> 20:53 it might be that you are missed qt5translations-l10n before
> 20:53
> or how the package is called
> 
> shirish
> 20:53
> right.
> 
> A agaida (IRC)
> 20:54
> i improved the packaging a bit - and now depend on this package instead only recommend it
> 
> 20:55
> lesson learned - some users still call recommends "bloat"
> 
> shirish
> 20:55
> right, I usually leave translation packages alone as don't need it.
> 
> A agaida (IRC)
> 20:55
> so if one install: apt install lxqt --no-install-recommends there was some fallout in every installation
> 
> shirish
> 20:55
> unless I am doing something other than english installation for a user.
> 
> A agaida (IRC)
> 20:56
> but qt5translations-l10n is also about shortcut handling
> 20:56
> took me some days to figure it out :D
> 
> shirish
> 20:56
> let me guess unicode keys etc. ?
> 20:57
> I learn that whole accent stuff and all just some days ago.
> 20:58
> hadn't known about it ever.
> 
> A agaida (IRC)
> 20:58
> not only
> 20:58
> qt5t..-l10n handle translation of menu shortcuts - as in 
> 20:59
> LANG=C &Menu - will work in english

**Comment by shirishag75** [comment] 2018-10-15 07:12
It doesn't fix the drop-down problem but yeah at least you can work with shortcuts :)

**Comment by tsujan** [comment] 2018-10-15 07:38
FYI

I'm on gnome-shell+Xorg now and the dropdown mode works fine with `f1`. It also works when I change the desktop, whether it's empty or not.

**Comment by agaida** [comment] 2018-10-15 08:04
hmm - i wrote: first issue solved - that means there are other issues. It seems we have a timing issue with the dropdown and key-events. So in a first step i checked only the behaviour, not the code - easy to reproduce:
* qterminal -d
* hit <shortcut> several times - one will notice somewhen that the event is processed, but wrong in the sense of: visible/not visible/v/n/v/n/v/n/v/n/v/v/v/n
that means - in some point the application shortly disappear and return to screen - after such an event everything is ok for the next n hits and so on

**Comment by shirishag75** [comment] 2018-10-15 08:29
At my end both 'Shift+F12' or if I use 'F12' its unresponsive or behaves like a 'dead key' . If needed could do a 

`$ timeout 120s strace qterminal `

in the hopes it gives some insight than not got before.

**Comment by yan12125** [comment] 2018-10-15 10:41
> hit several times

Thanks! I can reproduce it now with Arch + LXQt.

**Comment by shirishag75** [comment] 2018-10-23 07:14
It's 0.14.0~really~0.9.1~157-gee250b4-1 now actually but still the issue remains.

**Comment by ranjan-purbey** [comment] 2019-02-19 18:43
The problem might be related to Wayland. See here: https://github.com/Guake/guake/issues/994#issuecomment-328914578

**Comment by shirishag75** [comment] 2019-02-19 20:10
uh oh, seems to be one of the problems whose solution don't seem will come up easily :(

**Comment by tsujan** [comment] 2019-02-19 22:05
> uh oh, seems to be one of the problems whose solution don't seem will come up easily :(

It needs a developer that can reproduce and see it first hand. As implied above, `F1` has always worked fine here, although I tested `F12` too but couldn't see a problem.

Unfortunately, there can be various causes for the behavior reported here but the report itself didn't help in narrowing them down -- on the contrary, this page became a mixture of various comments.

**Comment by ranjan-purbey** [comment] 2019-02-20 15:11
> The problem might be related to Wayland. See here: [Guake/guake#994 (comment)](https://github.com/Guake/guake/issues/994#issuecomment-328914578)

If this is the case, one solution can be to allow only one instance of the terminal in drop down mode and show the already running instance when shortcut key is pressed. This way, one can add a new shortcut in Gnome keyboard settings to trigger "qterminal -d", as they're currently doing with Guake.

**Comment by ArenT1981** [comment] 2019-02-21 21:26
I can confirm that I also have this exact same issue on my two laptops running qterminal under LXQt. (0.9.0, QT 5.

I haven't yet been able to identify any particular specific set of events that trigger the problem. It does seem related to lots of (normal) keyboard activity (e.g. like typing this post).

Qterminal will be working perfectly, F12 popping it up and down flawlessly, then randomly, it will just stop working. It is a real pity, as I think this is an outstanding project, I love the configurability of this terminal! I'm still using it desite this nuisance issue and have it set to autostart by LXQt.

Is there no shell command I can issue from another terminal to force the redisplay/foreground it back on-screen in X?

`ps aux | grep ` issued in a fresh terminal reports that the `qterminal --drop` process is indeed still running, so it hasn't crashed. It just appears that the event handler/listener for the F12 key has borked up.

**Comment by ArenT1981** [comment] 2019-02-21 21:30
Addendum. It might not be relevant, but I decided to start it from another terminal in order to try and capture any stdout, and in fact the problem reoccurred whilst typing the above post (irony!). i.e. it was working before I typed the post, then no longer afterward.

I do have the following error message showing eight times with the same timestamp, and I would hazard to guess it may well have been at this exact point the drop down key stopped working:
```

** (qterminal:7853): WARNING **: 21:17:12.137: invalid source position for vertical gradient

** (qterminal:7853): WARNING **: 21:17:12.137: invalid source position for vertical gradient

** (qterminal:7853): WARNING **: 21:17:12.140: invalid source position for vertical gradient

** (qterminal:7853): WARNING **: 21:17:12.140: invalid source position for vertical gradient

** (qterminal:7853): WARNING **: 21:17:12.561: invalid source position for vertical gradient

** (qterminal:7853): WARNING **: 21:17:12.561: invalid source position for vertical gradient

** (qterminal:7853): WARNING **: 21:17:12.564: invalid source position for vertical gradient
```

Don't know whether this is of any help.

**Comment by agaida** [comment] 2019-03-13 17:20
The problem goes far deeper and there are some other problems with the drop-down mode. So i guess this issue will take time and a lot of patience. (Btw. i can reproduce the issue partly - not ever, but from time to time)

**Comment by shirishag75** [comment] 2019-03-13 18:54
I did try and still have issues. Since then I have gone back to guake even though it has its own set of issues, simply due to the drop-down issue in qterminal. Sadly, I haven't had time lately and also lxqt is back into the development mode it probably would not make much sense to try to figure out things more. 

I'll probably lie low till Debian is released. Once that is released, hopefully till that time lxqt development window might have started again and we may again try and test things and see what works and breaks. I do hope the strace I shared was of some help.  FWIW, I have moved back to Debian repo. instead of using the upstream repo. as I wanna help out in case there are issues with the debian release. 

```
$ apt-cache policy qterminal
qterminal:
  Installed: 0.14.1-1
  Candidate: 0.14.1-1
  Version table:
 *** 0.14.1-1 990
        990 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages
        500 http://cdn-fastly.deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by alan12345678** [comment] 2020-04-14 20:29
a very non-technical bit of input, but I seem to have stumbled upon something that helps this issue (while looking for something different). I read all of the above. I too have been having issues. Ah, I thought, perhaps F12 (my choice of key) is used elsewhere. So I tried setting F1 via the settings editor. It worked! However...

Noting that qterminal gets its colours from /usr/share/qterwidget5 inside $XDG_CONFIG_HOME is a directory qterminal.org, inside which is 'qterminal.ini'.

I scrolled down this list to discover that there was an entry for the show/hide shortcut. This was still set to F12. Opening up prefs from Qterminal itself (right click) showed it was F1.

I decided to edit the value in qterminal.ini, after which... the F1 key stopped working i.e. reverted back to the exact same flickering behaviour that F12 had exhibited.

Somewhere between these THREE places that store the shortcut, perhaps lies part of the reason why in certain distros it's a problem. I've now got the key working here at F12 but ONLY BECAUSE the .ini file has a value of F1! Confusing, but true! If I change the value in .ini to F12, it renders the settings manager gui unable to set the value, as all I get is a countdown in the window, and not able to set a value.

Hope this helps - apologies for the long form explanations.

**Comment by hyiltiz** [comment] 2021-07-22 14:14
Steps:
- Reboot and log into LXQT
- Open QTerminal from the `lxqt-panel` application menu
- Opened QTerminal Preferences > Dropdown and confirm it said `F12`
- Press `F12` and observe a `~` show up in the terminal as an input character
- From the lxqt-panel, go to a blank empty desktop workspace from via lxqt-panel (so Firefox etc. hopefully won't capture `F12` keypress)
- Press `F12`, and observe nothing happens.
- Go back to QTerminal, and from within run `xterm`
- From within `xterm` run `qterminal -d`
- Pressing `F12` and observe the `qterminal -d` window toggle off
- Press `F12` and the dropdown terminal comes back
- Highlight something else (like `PCManFM-Qt`) and press `F12` again to see `F12` works to toggle the dropdown

## Fix

This is just confirming what @agaida pointed out earlier works; somehow, when launching QTerminal from the lxqt-panel, it is a *normal terminal* (whatever that means... Does it mean login terminal, tty emulator or something else?) but launching one from within `xterm` apparently works. Note that if you launch `qterminal` (instead of `qterminal -d`) from within `xterm`, then it doesn't work either, i.e. a normal QTerminal "app/window" cannot transform and become a dropdown version.

## Env
- Ubuntu 20.04
- QTerminal 0.14.1
- DE (logged in and being used): LXQT 0.14.1

**Comment by tsujan** [comment] 2021-07-22 14:54
> Press F12 and observe a ~ show up in the terminal as an input character

Of course, it should. The shortcut isn't for launching the drop-down mode but for *showing* its window while its process is running in the background.

> QTerminal 0.14.1

Very outdated.

To this day, I haven't been able to reproduce any problem with F12 or other shortcuts for showing the drop-down window. Apart from @agaida (who doesn't work with LXQt anymore), can any LXQt member reproduce the main issue reported here? If not, please close it.

**Comment by hyiltiz** [comment] 2021-07-22 15:02
Yeah Ubuntu LTS is a bad thing to write issues/bug reports from; :( bear with me pls...

At this point, I am guessing it was just a misaligned expectation from the beginning: some users might've thought they can *switch* on/off any QTerminal instance, while the implemented behavior simply *brings back/hides* a running `qterminal -d` instance. As a user, I'd vote for closing it too.

**Comment by tsujan** [comment] 2021-07-22 15:12
> some users might've thought they can switch on/off any QTerminal instance

Before your previous comment, I couldn't guess that. I agree with you; most probably, it has been about mistaking "showing" for "launching" from the beginning.

QTerminal has two desktop entries (= two items in the main menu): one for the usual terminal, the other for the drop-down mode.

**Closed by tsujan** 2021-07-22 15:12 UTC
Labels: bug

**Comment by yan12125** [comment] 2021-07-22 15:53
I remember I could reproduce the issue 3 years ago (https://github.com/lxqt/qterminal/issues/491#issuecomment-429799479) by hitting F12 10~20 times. With the latest git version, I cannot reproduce the issue after hitting F12 more than 100 times. I assume this has been somehow fixed.

**Comment by tsujan** [comment] 2021-07-22 16:46
@yan12125 
A mixture of different causes may have been at play here:

 1. Some users may have mistaken "showing" for "launching" and thought that `F12` should show a drop-down window even if they haven't started the drop-down instance (I think that's the main cause);
 2. The shortcut may have been already in use; or
 3. There may have been an issue that's fixed now (as you suggested).

**Comment by yan12125** [comment] 2021-07-22 17:46
Yeah I know. I just ignore parts that are irrelevant to the original issue
:)

tsujan ***@***.***> 於 2021年7月23日 週五 上午12:46寫道：

**Comment by entangledloops** [comment] 2023-06-04 16:14
Why did this get closed? Still an issue today. After some time, F12 just stops working. I can see process is still alive. If I kill it manually and restart, fixes it for a while until it happens again. It's really sad because it's an important feature for me that I use daily, and I actually prefer it to Guake.

**Comment by entangledloops** [comment] 2023-06-04 16:16
> 

I can reproduce it fairly reliably. It happens to me an average of once per day. Is there some logging or flags I can use that would help debug this?

**Comment by tsujan** [comment] 2023-06-04 16:29
> 0.17.0

It's archaic.

**Comment by entangledloops** [comment] 2023-06-04 16:45
@tsujan I see. I guess I'll build from source then. I wonder why this is latest stable build pulled by Ubuntu?

**Comment by tsujan** [comment] 2023-06-04 17:28
> I guess I'll build from source then.

And `qtermwidget` before it.

But there may be up-to-date PPA builds somewhere (I don't know about Ubuntu).

**Comment by stefonarch** [comment] 2023-06-04 17:55
> But there may be up-to-date PPA builds somewhere (I don't know about Ubuntu).

If you're using 22.04 https://lubuntu.me/jammy-backports-22-04-1-lxqt-1-2/
