### ISSUE TITLE
Preset not working

### ISSUE THREAD

**Issue by akane-sora** [lxqt/qterminal#706] opened 2020-09-18 22:13 UTC
The problem is simple, I set start with preset: "2 terminals vertically" and it just not work.

##### System Information

* Distribution & Version: kali-linux
* Kernel: Linux kali 5.7.0-kali3-amd64 #1 SMP Debian 5.7.17-1kali1 (2020-08-26) x86_64 GNU/Linux
* Qt Version: 
* qtermwidget Version: 0.14.1
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment] 2020-09-18 22:27
Duplicate of https://github.com/lxqt/qterminal/issues/351

Apparently, https://github.com/lxqt/qterminal/pull/352 isn't complete.

**Closed by tsujan** 2020-09-18 22:27 UTC
