### ISSUE TITLE
Graphics bug when use autocomplete (when you use Tab)

### ISSUE THREAD

**Issue by Sanchous1295** [lxqt/qterminal#1042] opened 2023-03-30 17:14 UTC
##### Expected Behavior
I'm trying to update my packages on Linux and after that my qTerminal is broken.
When I press tab to autocomplete a command, if the number of options is more than 1, then part of the command remains on the line

example 
i write `su`
![image](https://user-images.githubusercontent.com/120050877/228905307-13ffa6ea-87cd-4fc3-bac8-b16c9c4e0fc7.png)

after that i press Tab
![image](https://user-images.githubusercontent.com/120050877/228905019-955abde8-85b2-4961-8bea-9a7baeb95454.png)

as you see part of the command remains
![image](https://user-images.githubusercontent.com/120050877/228905637-fd73d49c-0dd8-4802-bbb1-5baba48ab481.png)

Also, this part can't be removed.
![image](https://user-images.githubusercontent.com/120050877/228906205-8587f40f-2833-47fd-87b5-b6baba223652.png)
in this image my line is empty 

It seems like graphics bug or something like that 

if i try autocomplete with 1 result, all is ok
![image](https://user-images.githubusercontent.com/120050877/228911917-cc73b89f-d4f0-4fc1-bec1-a4d523fbd1c6.png)
Press Tab
![image](https://user-images.githubusercontent.com/120050877/228912045-d9043fcf-2597-48c6-b56d-ffa5458b1eda.png)

##### System Information

* QTerminal version: 1.2.0-2
* Distribution & Version: Kali linux 5.14.0-kali4-amd64 SMP Debian 5.14.16-1kali1 (2021-11-05) x86_64 GNU/Linux

**Comment by hydrargyrum** [comment] 2023-03-30 18:56
Did you try with another terminal?

I can be wrong, but I've had this kind of issue with multiple terminals, and it's often an issue with the prompt and the shell that interact poorly. Typically, the shell assumes some length of the prompt, but the length is wrong because it assumes the color control chars take space, while they have zero-width.

**Comment by yan12125** [comment] 2023-06-05 19:31
> I can be wrong, but I've had this kind of issue with multiple terminals, and it's often an issue with the prompt and the shell that interact poorly. Typically, the shell assumes some length of the prompt, but the length is wrong because it assumes the color control chars take space, while they have zero-width.

This sounds likely. Could you check?

**Comment by yan12125** [comment] 2023-06-18 08:28
Closing assuming the issue is not caused by qterminal. Feel free to leave a comment or open a new issue if that happens only on qterminal.

**Closed by yan12125** 2023-06-18 08:28 UTC
Labels: feedback required
