### ISSUE TITLE
chinese text show issue

### ISSUE THREAD

**Issue by qiuzhiqian** [lxqt/qterminal#336] opened 2017-06-16 08:13 UTC
The height of the Chinese text display is incomplete.
OS:Archlinux
Linux version:4.11.3
WM:i3wm
![virtualbox_2017-06-16_16-11-39](https://user-images.githubusercontent.com/19386888/27217973-b4fc5744-52ae-11e7-82b1-0e9ea537d1b8.png)

**Comment by yan12125** [comment] 2017-06-16 08:25
Seems a duplicate of https://github.com/lxde/qtermwidget/issues/46

**Closed** 2018-09-23 09:34 UTC
