### ISSUE TITLE
At times qterminal hangs for a while. 

### ISSUE THREAD

**Issue by shirishag75** [lxqt/qterminal#497] opened 2018-10-15 13:18 UTC
For reasons unknown at times, qterminal hangs for a while. It is almost as the focus on qterminal has been lost. 

The only option is to click on the tabs for a while (fiddle around) and then the focus returns to the terminal and you can use it as you were using before. 

Package: qterminal
Version: 0.14.0~really~0.9.1~156-ga968cc4-1
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing-debug
  APT policy: (500, 'testing-debug'), (500, 'testing'), (100, 'unstable-debug'), (100, 'experimental-debug'), (100, 'experimental'), (100, 'unstable')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages qterminal depends on:
ii  libc6              2.27-6
ii  libqt5core5a       5.11.1+dfsg-9
ii  libqt5dbus5        5.11.1+dfsg-9
ii  libqt5gui5         5.11.1+dfsg-9
ii  libqt5widgets5     5.11.1+dfsg-9
ii  libqt5x11extras5   5.11.1-2
ii  libqtermwidget5-0  0.14.0~really~0.9.1~71-g871d069-1
ii  libstdc++6         8.2.0-7
ii  libx11-6           2:1.6.7-1

Versions of packages qterminal recommends:
ii  qterminal-l10n  0.14.0~really~0.9.1~156-ga968cc4-1

qterminal suggests no packages.

-- no debconf information

**Comment by shirishag75** [comment] 2018-11-01 18:36
just right now it happened again, this was after I had closed after the confirmation but still it hung around, after a minute or so the image disappared. Maybe some sort of garbage collection issue or something else, have no clue .

**Comment by tsujan** [comment] 2018-11-01 19:00
Unlike a crash, a hang is something that should be reproducible for it to be fixed. I'm afraid, unless you describe a way of reproducing it, nothing could be done.

I use qterminal -- and only qterminal -- on a regular basis. As a developer, I have to compile programs a lot and I do it only with qterminal -- for example, minutes ago, I was using qterminal and minutes later, I'll use it again -- but I've never encountered a hang.

> but still it/the image hung around, after a minute or so the image disappeared.

Which image?

**Comment by shirishag75** [comment] 2018-11-01 19:38
image of the terminal.

**Comment by tsujan** [comment] 2018-11-01 19:42
Then it's totally unrelated to qterminal or LXQt. I guess something is wrong with the WM and/or compositor you use or, perhaps, the compositor -- if any -- isn't configured correctly.

I close this but feel free to add comments.

**Closed by tsujan** 2018-11-01 19:42 UTC

**Comment by tsujan** [comment] 2018-11-01 19:43
The first thing I would check if I were you is whether 2 compositors are active. There are many other possibilities too.

**Comment by shirishag75** [comment] 2018-11-02 05:03
how do I check that ? According to Stephen Kitt in a similar question asked said there can only be one compoistor active at any one time, although I have asked the same at https://unix.stackexchange.com/questions/479222/is-there-a-way-to-know-if-more-than-one-compositor-is-running-in-a-session

**Comment by tsujan** [comment] 2018-11-02 07:37
> how do I check that ?

You could check LXQt Session Settings. If your Window Manager has a compositor (like kwin does), no other compositor (like Compton) should have been enabled there.

Please note that what I said was just one guess among many. Since you said you saw the "hung image" of qterminal, a problem with compositing came to my mind but, of course, I can't be sure.
