### ISSUE TITLE
Keyboard shortcuts when menu bar is hidden.

### ISSUE THREAD

**Issue by AbrahamAriel** [lxqt/qterminal#220] opened 2016-04-16 03:24 UTC
As the title said, none of the keyboard shortscut that I've tried (new tab, new window) works when I hide the menu bar.

**Comment by pmattern** [comment] 2016-04-16 16:07
Cannot confirm your findings running lxde/qtermwidget@3bfdfe8 and lxde/qterminal@67e2ba1 on Arch Linux.
All kinds of keyboard shortcuts, e. g. open new tab / window or switch tab, are working flawlessly when the menu bar is hidden, no matter whether it was hidden from the preferences or by keyboard shortcut.

To further track this down we need to know the OS you're running and which way QTermWidget and QTerminal were installed.

**Comment by acrox999** [comment] 2016-04-16 16:22
Sorry, I'll try to be as specific as I can. I'm using Arch Linux ARM (ALARM) on Raspberry Pi 3. Both QTermWidget and QTerminal were installed using the PKGBUILD from AUR (actual Arch's AUR).

**Comment by pmattern** [comment] 2016-04-16 22:43
None of the AUR packages qterm{widget,inal}{,-git} states some ARM architecture in its PKGBUILD. This could be due to the fact that nobody tested so far but also because these architectures just aren't supported. This is pointing to the actual underlying problem, IMO:

This issue boils down to the question whether or not QTerminal is supported on ARM.
Personally, I haven't got an ARM device at hand atm and can't read it from the code either. For the time being you may want to look whether other Qt applications behave similarily which could hint at a problem of Qt on ARM devices.

**Comment by r-a-v-a-s** [comment] 2016-05-24 22:34
Using the qterminal downloaded and installed on openSUSE it says it is version 0.6.0.
When I build from source it says I'm using 0.5.0... :astonished: 

Using the installed 0.6.0 I can confirm that the shortcuts do not work when the menu bar is hidden.

Using 0.5.0 built from source it works fine...

**Comment by agaida** [comment] 2016-05-24 22:38
@r-a-v-a-s  - this is not fixed if one use the distributed (released) version and build from this sources ...

**Comment by rexso** [comment] 2016-06-27 11:30
Confirmed on Gentoo (x86_64).
None of the shortcuts work when the menubar is hidden (not even the toggle menubar shorcut) for QTerminal 0.6.0 built from source.

**Comment by f2404** [comment] 2016-06-27 11:40
@rexso Were it the git sources that you've built? Have you also build qtermwidget from git sources?

**Comment by rexso** [comment] 2016-06-27 13:12
@f2404 Yes, I built both from the git sources

**Comment by f2404** [comment] 2016-06-27 13:13
That's weird because all shortcuts are working for me on Arch Linux.

**Comment by rexso** [comment] 2016-06-27 13:18
@f2404 All shortcuts work fine when the menubar is visible, but not when hidden.

**Comment by f2404** [comment] 2016-06-27 13:20
No, for me their work does not depend on the menubar visibility.

Can you maybe see anything weird in the qterminal output if you run it from another terminal? in the ~/.xsession-errors file?

**Comment by rexso** [comment] 2016-06-27 13:29
@f2404 Nothing in neither..

When trying paste (ctrl+shift+v) for instance, having the menu bar visible, the following is printed out:
TermWidget(0x1a2be80) current terminal

while nothing is printed out if the menu bar is hidden. Instead, the key sequence is shown literally in the prompt, such as: ^V

**Comment by f2404** [comment] 2016-06-27 13:43
@rexso I'm not seeing `TermWidget(0x1a2be80) current terminal` message when pasting. Instead, I'm seeing this message has been removed in this commit: https://github.com/lxde/qterminal/commit/74b1ccdde1d9b86b00f9a1506b0eae7ca25f3435
It seems you are not using the latest git sources when building.

**Comment by rexso** [comment] 2016-06-27 13:54
@f2404 Indeed I didn't use the lastest commit, but the lastest release (0.6.0),
which is 111 commits behind master. Guess I could try pulling the lastest and build from that.

**Comment by f2404** [comment] 2016-06-27 13:56
Please also check qtermidget as it has also been taken far from the latest release.

**Comment by f2404** [comment] 2016-06-28 13:28
@rexso Are you fine now?

**Comment by Luke-Nukem** [comment] 2016-08-28 04:29
I'm confirming this on Manjaro 16.06;

* qterminal - v0.6.0
* LXQT - v0.10
    + Using BSPWM as the window manager
    + LX Global shortcuts disabled
    + LX desktop disabled
* SXHKD is used for shortcuts to control BSPWM

Disabling the menubar kills my ability to use the shortcuts, this also happens with a clean, newly created user using stock (/etc/skel) provided settings.

**Comment by pmattern** [comment] 2016-08-28 08:55
It pretty much looks like this issue is fixed in recent `master`. So any chance you can test latest checkouts of both QTermWidget and QTerminal? The corresponding [AUR](https://aur.archlinux.org/) packages [qtermwidget-git](https://aur.archlinux.org/packages/qtermwidget-git/) and [qterminal-git](https://aur.archlinux.org/packages/qterminal-git/) should work on Manjaro, too.

Desktop environment, window manager and all that stuff shouldn't bee involved as long as the shortcuts work flawlessly when the menu bar is not hidden.

**Comment by stefonarch** [comment] 2022-01-31 17:45
Reopen if still present.

**Closed by stefonarch** 2022-01-31 17:45 UTC
